import type { Alert } from '@/types/alerts';

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'A001',
    title: 'Low SOC Warning',
    description: 'Battery at 18% — charge soon to avoid deep discharge.',
    category: 'critical',
    severity: 'warning',
    timestamp: new Date(Date.now() - 2 * 60 * 1000),
    read: false,
    dismissible: true,
    vin: 'VOLT1EV001234',
    roles: ['CUSTOMER'],
  },
  {
    id: 'A002',
    title: 'Service Due Soon',
    description: 'Routine service due in 320 km or 14 days.',
    category: 'service',
    severity: 'warning',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    read: false,
    dismissible: true,
    roles: ['CUSTOMER', 'DEALER'],
  },
  {
    id: 'A003',
    title: 'Insurance Renewal',
    description: 'Vehicle insurance expires in 28 days.',
    category: 'documents',
    severity: 'info',
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    read: true,
    dismissible: true,
    roles: ['CUSTOMER'],
  },
  {
    id: 'A004',
    title: 'Thermal Runaway Alert',
    description: 'Critical BMS fault on VIN VOLT1EV009912.',
    category: 'critical',
    severity: 'critical',
    timestamp: new Date(Date.now() - 30 * 60 * 1000),
    read: false,
    dismissible: false,
    vin: 'VOLT1EV009912',
    roles: ['VOLT', 'DEALER'],
  },
  {
    id: 'A005',
    title: 'Breakdown Reported',
    description: 'Customer reported breakdown near Tonk Road, Jaipur.',
    category: 'service',
    severity: 'critical',
    timestamp: new Date(Date.now() - 45 * 60 * 1000),
    read: false,
    dismissible: false,
    roles: ['DEALER', 'VOLT'],
  },
  {
    id: 'A006',
    title: 'Default Risk — Inactive 12 days',
    description: 'Financed vehicle VOLT1EV007821 inactive for 12 days.',
    category: 'critical',
    severity: 'warning',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    read: false,
    dismissible: true,
    vin: 'VOLT1EV007821',
    roles: ['FINANCIER', 'VOLT'],
  },
  {
    id: 'A007',
    title: 'Trip Summary Ready',
    description: 'Your weekly trip report is available.',
    category: 'trips',
    severity: 'info',
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    read: true,
    dismissible: true,
    roles: ['CUSTOMER'],
  },
];
